// src/env.mjs
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_HOST: z.string().nonempty(),
    DATABASE_USER: z.string().nonempty(),
    DATABASE_PASS: z.string().nonempty(),
    DATABASE_NAME: z.string().nonempty(),
    POSTGRES_DATABASE: z.string().nonempty(),
    POSTGRES_URL: z.string().nonempty(),
    POSTGRES_URL_NON_POOLING: z.string().nonempty(),
    POSTGRES_PRISMA_URL: z.string().nonempty(),
    POSTGRES_USER: z.string().nonempty(),
    POSTGRES_PASSWORD: z.string().nonempty(),
    POSTGRES_HOST: z.string().nonempty(),
    PROPELAUTH_VERIFIER_KEY: z.string().nonempty(),
    PROPELAUTH_REDIRECT_URI: z.string().url(),
    PROPELAUTH_API_KEY: z.string().nonempty(),
    NESTJS_BASE_API_URL: z.string().url(),
    KV_URL: z.string().nonempty(),
    KV_REST_API_URL: z.string().url(),
    KV_REST_API_TOKEN: z.string().nonempty(),
    KV_REST_API_READ_ONLY_TOKEN: z.string().nonempty(),
  },
  client: {
    NEXT_PUBLIC_AUTH_URL: z.string().url(),
    NEXT_PUBLIC_NESTJS_BASE_API_URL: z.string().url(),
  },
  runtimeEnv: {
    DATABASE_HOST: process.env.DATABASE_HOST,
    DATABASE_USER: process.env.DATABASE_USER,
    DATABASE_PASS: process.env.DATABASE_PASS,
    DATABASE_NAME: process.env.DATABASE_NAME,
    POSTGRES_DATABASE: process.env.POSTGRES_DATABASE,
    POSTGRES_URL: process.env.POSTGRES_URL,
    POSTGRES_URL_NON_POOLING: process.env.POSTGRES_URL_NON_POOLING,
    POSTGRES_PRISMA_URL: process.env.POSTGRES_PRISMA_URL,
    POSTGRES_USER: process.env.POSTGRES_USER,
    POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
    POSTGRES_HOST: process.env.POSTGRES_HOST,
    PROPELAUTH_VERIFIER_KEY: process.env.PROPELAUTH_VERIFIER_KEY,
    PROPELAUTH_REDIRECT_URI: process.env.PROPELAUTH_REDIRECT_URI,
    PROPELAUTH_API_KEY: process.env.PROPELAUTH_API_KEY,
    NESTJS_BASE_API_URL: process.env.NESTJS_BASE_API_URL,
    KV_URL: process.env.KV_URL,
    KV_REST_API_URL: process.env.KV_REST_API_URL,
    KV_REST_API_TOKEN: process.env.KV_REST_API_TOKEN,
    KV_REST_API_READ_ONLY_TOKEN: process.env.KV_REST_API_READ_ONLY_TOKEN,
    NEXT_PUBLIC_AUTH_URL: process.env.NEXT_PUBLIC_AUTH_URL,
    NEXT_PUBLIC_NESTJS_BASE_API_URL:
      process.env.NEXT_PUBLIC_NESTJS_BASE_API_URL,
  },
});
